# Generated by Django 5.0.7 on 2024-07-15 14:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_gene_name_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
