# Generated by Django 5.0.7 on 2024-07-26 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_formula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
