# Generated by Django 5.0.7 on 2024-08-08 14:04

from django.db import migrations

def set_is_staff(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for user in User.objects.all():
        if (user.role == "Admin"):
            # Set is_staff to True or False as needed
            user.is_staff = True  # or False
            user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_is_staff'),  # Replace with the actual last migration file in the users app
    ]

    operations = [
        migrations.RunPython(set_is_staff),
    ]
