# Generated by Django 5.0.6 on 2024-07-03 09:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=240)),
                ('username', models.CharField(max_length=240)),
                ('password', models.CharField(max_length=240)),
                ('role', models.CharField(max_length=240)),
                ('isDeactivated', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('registrationDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
