# Generated by Django 5.0.6 on 2024-07-09 13:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneData',
            fields=[
                ('geneID', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('encrypted_sequence', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=240, unique=True),
        ),
    ]
